import React from 'react';
import { X, Package, User, Calendar, Building, Hash, Barcode, Download } from 'lucide-react';
import { IssuedProperty } from '../types';
import jsPDF from 'jspdf';

interface IssuedPropertyDetailsProps {
  issuedProperty: IssuedProperty;
  onClose: () => void;
}

const IssuedPropertyDetails: React.FC<IssuedPropertyDetailsProps> = ({ issuedProperty, onClose }) => {
  const generateIssuanceReport = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const margin = 20;

    // Header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('ISSUED PROPERTY DETAILS', pageWidth / 2, 30, { align: 'center' });
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.text('Ethiopian Defence University', pageWidth / 2, 45, { align: 'center' });
    doc.text('Institute of Research and Development (IRD)', pageWidth / 2, 55, { align: 'center' });

    // Property Information
    let yPos = 80;
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Property Information', margin, yPos);
    
    yPos += 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    
    const propertyInfo = [
      ['Property Number:', issuedProperty.propertyNumber],
      ['Property Name:', issuedProperty.propertyName],
      ['Model Number:', issuedProperty.modelNumber],
      ['Model 19 Number:', issuedProperty.model19Number],
      ['Model 22 Number:', issuedProperty.model22Number],
      ['Serial Number:', issuedProperty.serialNumber],
      ['Quantity Type:', issuedProperty.quantityType],
      ['Issued Quantity:', `${issuedProperty.issuedQuantity}`]
    ];

    propertyInfo.forEach(([label, value]) => {
      doc.setFont('helvetica', 'bold');
      doc.text(label, margin, yPos);
      doc.setFont('helvetica', 'normal');
      doc.text(value, margin + 60, yPos);
      yPos += 10;
    });

    // Recipient Information
    yPos += 10;
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Recipient Information', margin, yPos);
    
    yPos += 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    
    const recipientInfo = [
      ['Name:', issuedProperty.userName],
      ['Department:', issuedProperty.userDepartment],
      ['Issuance Date:', new Date(issuedProperty.issuedAt).toLocaleDateString()],
      ['Issuance Time:', new Date(issuedProperty.issuedAt).toLocaleTimeString()]
    ];

    recipientInfo.forEach(([label, value]) => {
      doc.setFont('helvetica', 'bold');
      doc.text(label, margin, yPos);
      doc.setFont('helvetica', 'normal');
      doc.text(value, margin + 60, yPos);
      yPos += 10;
    });

    // Store Manager Information
    yPos += 10;
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Issued By', margin, yPos);
    
    yPos += 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    
    doc.setFont('helvetica', 'bold');
    doc.text('Store Manager:', margin, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(issuedProperty.storeManagerName, margin + 60, yPos);
    yPos += 10;
    
    doc.setFont('helvetica', 'bold');
    doc.text('Date & Time:', margin, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(new Date(issuedProperty.issuedAt).toLocaleString(), margin + 60, yPos);

    // Property Type
    yPos += 15;
    doc.setFont('helvetica', 'bold');
    doc.text('Property Type:', margin, yPos);
    doc.setFont('helvetica', 'normal');
    const propertyType = issuedProperty.isPermanent ? 'Permanent' : 'Temporary';
    doc.text(propertyType, margin + 60, yPos);

    // Footer
    yPos = doc.internal.pageSize.height - 30;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('This is an official document generated by IRD Properties Management System', pageWidth / 2, yPos, { align: 'center' });

    // Save the PDF
    doc.save(`Issued_Property_${issuedProperty.propertyNumber}_${issuedProperty.userName.replace(/\s+/g, '_')}.pdf`);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-3">
          <div className="w-12 h-12 bg-primary-100 rounded-xl flex items-center justify-center">
            <Package className="w-7 h-7 text-primary-600" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Issued Property Details</h1>
            <p className="text-gray-600">Property #{issuedProperty.propertyNumber}</p>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <button
            onClick={generateIssuanceReport}
            className="flex items-center px-4 py-2 bg-secondary-600 hover:bg-secondary-700 text-white font-medium rounded-lg transition-colors"
          >
            <Download className="w-4 h-4 mr-2" />
            Download Report
          </button>
          <button
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <X className="w-6 h-6" />
          </button>
        </div>
      </div>

      {/* Property Information */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Details */}
        <div className="lg:col-span-2 space-y-6">
          {/* Property Information */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Property Information</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="flex items-start space-x-3">
                <Hash className="w-5 h-5 text-gray-400 mt-1 flex-shrink-0" />
                <div>
                  <p className="text-sm text-gray-500">Property Number</p>
                  <p className="font-medium text-gray-900">{issuedProperty.propertyNumber}</p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <Package className="w-5 h-5 text-gray-400 mt-1 flex-shrink-0" />
                <div>
                  <p className="text-sm text-gray-500">Property Name</p>
                  <p className="font-medium text-gray-900">{issuedProperty.propertyName}</p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <Barcode className="w-5 h-5 text-gray-400 mt-1 flex-shrink-0" />
                <div>
                  <p className="text-sm text-gray-500">Model Number</p>
                  <p className="font-medium text-gray-900">{issuedProperty.modelNumber}</p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <Barcode className="w-5 h-5 text-gray-400 mt-1 flex-shrink-0" />
                <div>
                  <p className="text-sm text-gray-500">Model 19 Number</p>
                  <p className="font-medium text-gray-900">{issuedProperty.model19Number}</p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <Barcode className="w-5 h-5 text-blue-500 mt-1 flex-shrink-0" />
                <div>
                  <p className="text-sm text-gray-500">Model 22 Number</p>
                  <p className="font-medium text-gray-900">{issuedProperty.model22Number}</p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <Barcode className="w-5 h-5 text-gray-400 mt-1 flex-shrink-0" />
                <div>
                  <p className="text-sm text-gray-500">Serial Number</p>
                  <p className="font-medium text-gray-900">{issuedProperty.serialNumber}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Issuance Details */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Issuance Details</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <p className="text-sm text-gray-500 mb-2">Quantity Type</p>
                <p className="text-lg font-medium text-gray-900 capitalize">{issuedProperty.quantityType}</p>
              </div>
              <div>
                <p className="text-sm text-gray-500 mb-2">Issued Quantity</p>
                <p className="text-lg font-medium text-gray-900">
                  {issuedProperty.issuedQuantity} {issuedProperty.quantityType}
                </p>
              </div>
              <div>
                <p className="text-sm text-gray-500 mb-2">Issuance Date</p>
                <p className="text-lg font-medium text-gray-900">
                  {new Date(issuedProperty.issuedAt).toLocaleDateString()}
                </p>
              </div>
              <div>
                <p className="text-sm text-gray-500 mb-2">Issuance Time</p>
                <p className="text-lg font-medium text-gray-900">
                  {new Date(issuedProperty.issuedAt).toLocaleTimeString()}
                </p>
              </div>
            </div>
          </div>

          {/* Property Type */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Classification</h3>
            <div className="flex items-center space-x-3">
              <span className={`px-3 py-1 text-sm font-medium rounded-full ${
                issuedProperty.isPermanent ? 'bg-blue-100 text-blue-800' : 'bg-gray-100 text-gray-800'
              }`}>
                {issuedProperty.isPermanent ? 'PERMANENT' : 'TEMPORARY'}
              </span>
              <p className="text-sm text-gray-500">
                {issuedProperty.isPermanent ? 'Durable and long-lasting items' : 'Consumable or short-term use items'}
              </p>
            </div>
          </div>
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          {/* Recipient Information */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Recipient Information</h3>
            <div className="space-y-4">
              <div className="flex items-start space-x-3">
                <User className="w-5 h-5 text-gray-400 mt-1 flex-shrink-0" />
                <div>
                  <p className="text-sm text-gray-500">Name</p>
                  <p className="font-medium text-gray-900">{issuedProperty.userName}</p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <Building className="w-5 h-5 text-gray-400 mt-1 flex-shrink-0" />
                <div>
                  <p className="text-sm text-gray-500">Department</p>
                  <p className="font-medium text-gray-900">{issuedProperty.userDepartment}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Store Manager Information */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Issued By</h3>
            <div className="space-y-4">
              <div className="flex items-start space-x-3">
                <User className="w-5 h-5 text-gray-400 mt-1 flex-shrink-0" />
                <div>
                  <p className="text-sm text-gray-500">Store Manager</p>
                  <p className="font-medium text-gray-900">{issuedProperty.storeManagerName}</p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <Calendar className="w-5 h-5 text-gray-400 mt-1 flex-shrink-0" />
                <div>
                  <p className="text-sm text-gray-500">Date & Time</p>
                  <p className="font-medium text-gray-900">
                    {new Date(issuedProperty.issuedAt).toLocaleString()}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default IssuedPropertyDetails; 